package net.pms.medialibrary.commons.enumarations;

public enum ConditionUnit {
	TIMESPAN_SECONDS,
	TIMESPAN_MINUTES,
	TIMESPAN_HOURS,
	TIMESPAN_DAYS,
	TIMESPAN_WEEKS,
	TIMESPAN_MONTHS,
	TIMESPAN_YEARS,

	FILESIZE_BYTE,
	FILESIZE_KILOBYTE,
	FILESIZE_MEGABYTE,
	FILESIZE_GIGABYTE,
	FILESIZE_TERABYTE,
	
	UNKNOWN
}
