package net.pms.medialibrary.commons.enumarations;

public enum FileProperty {
	UNKNOWN,

	//Video
	VIDEO_ORIGINALNAME,
	VIDEO_NAME,
	VIDEO_TMDBID,
	VIDEO_IMDBID,
	VIDEO_TAGLINE,
	VIDEO_OVERVIEW,
	VIDEO_BUDGET,
	VIDEO_REVENUE,
	VIDEO_DIRECTOR,
	VIDEO_YEAR,
	VIDEO_HOMEPAGEURL,
	VIDEO_TRAILERURL,
	VIDEO_CERTIFICATION,
	VIDEO_CERTIFICATIONREASON,
	VIDEO_RATINGPERCENT,
	VIDEO_RATINGVOTERS,
	VIDEO_COVERURL,
	VIDEO_GENRES,
	
	//Audio
	AUDIO_SONGNAME,
	AUDIO_ARTIST,
	AUDIO_ALBUM,
	AUDIO_GENRE,
	AUDIO_YEAR,
	AUDIO_COVERPATH,
	
	//Pictures
	PICTURES_WIDTH,
	PICTURES_HEIGHT
}
